id: P4A8FF45E
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: nl
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    5f06d78ce351442b92050c731589b689:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    63125369ba234cd5a5fcbb36f90bf6ca:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    4f7309d536f44ae0a74bb0d6846c7dc7:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    676269a1392e492a8dac089977407343:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    2ac4e8c261d34b278a62dcdbb4a1c1c5:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    7a039c4d7fb34171a58891451ad52d6c:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    143d9911383040a6849c60d57c5e2cb4:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    84cbeb7e02544b5ea26312d2f9ce17df:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    2d1d56678b954feca4cc6145add00334:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    4d0fdce8b27b49dea17c2992e9e0cc79:
      title: The Lament of Rudra
      parent: Confession
    2b516544422247b88ea29bf8beaf7b21:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    26bd54d19dbc4e3ebdf8aa8f59e124aa:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    0ad77cf8974244558f1bbac060511d8d:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    0d1844774e4c4722bc3c37fad2024ce7:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    4c8fa53084f846e8b43ba5529a473020:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    dc72182eb8e54afd916350190b2d00ac:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    0178e12fac3443cbb48a9a804f055e2a:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    8172aeb3d10c4fbfbe28ee9b3e32716d:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    6c3260a08adf43b2999bafb57cedc24d:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    7a3496a9ca264094ad6cc384f949e499:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    a04a51cd1fff46039cfff5d414aa06c4:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    e612f5f763744c2192037fafdf02292b:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    3e9489c29b444031a18b91773a06214b:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    ee4077caaacc42ab97f43eea53d9e9e6:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    e36fdb49a665449caeca6f98a53f7d80:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    973d6e601a7a42388a025205dbc083f9:
      title: The Twenty-Eight Commitments
      parent: Tantra
    a9fdbba36ed84d8487456695eff3f24e:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.944883'
last_modified_at: '2022-02-28T22:46:47.944886'
